#开发板用户名
BOARD_USER="debian"
#开发板IP地址
BOARD_IP="192.168.137.74"
#开发板目标目录
BOARD_DEST="/home/debian"
#虚拟机目标目录
LOCAL_DEST="/home/embedfire"
#Web服务地址
WEB_SERVER_URL="http://10.27.102.53:5000/api/data"
#截图上传地址
SCREENSHOT_SERVER_URL="http://192.168.137.1:5000/api/screenshot"
#与开发板交互时虚拟机选择net0
